# Generated by scripts/kaggle_run.py. Edit the repo, not this file.
import base64, io, os, subprocess, sys, tarfile

MODULE = "__MODULE__"
CONFIG = "__CONFIG__"
SEEDS = __SEEDS__
EXTRA_ARGS = __EXTRA_ARGS__
GIT_COMMIT = "__GIT_COMMIT__"
BUNDLE = "__BUNDLE__"

CODE, OUT = "/tmp/imolara", "/kaggle/working/outputs"
tarfile.open(fileobj=io.BytesIO(base64.b64decode(BUNDLE))).extractall(CODE)
subprocess.run([sys.executable, "-m", "pip", "install", "-q", "-r",
                f"{CODE}/requirements-kaggle.txt"], check=True)

import torch
assert torch.cuda.is_available(), "No GPU: check accelerator / phone verification"
print("GPU:", torch.cuda.get_device_name(0), "| torch", torch.__version__, flush=True)

os.makedirs(OUT, exist_ok=True)
with open(f"{OUT}/env.txt", "w") as f:  # exact package versions, for the report
    subprocess.run([sys.executable, "-m", "pip", "freeze"], stdout=f, check=True)

env = {**os.environ, "IMOLARA_GIT_COMMIT": GIT_COMMIT, "PYTHONUNBUFFERED": "1"}
import glob
emb = glob.glob("/kaggle/input/**/w2v_yo_300.kv", recursive=True)
if emb:  # attached imolara-embeddings dataset (scripts/kaggle_dataset.py)
    env["IMOLARA_EMB_DIR"] = os.path.dirname(emb[0])
    print("embeddings:", env["IMOLARA_EMB_DIR"], os.listdir(env["IMOLARA_EMB_DIR"]), flush=True)
for seed in SEEDS:
    print(f"=== {CONFIG} seed {seed} ===", flush=True)
    subprocess.run([sys.executable, "-m", MODULE, "--config", CONFIG, "--seed", str(seed),
                    "--output_dir", f"{OUT}/seed{seed}", *EXTRA_ARGS], cwd=CODE, env=env, check=True)
