"""Kaggle notebooks for one experiment (used by `scripts/kaggle_run.py`).

Two notebooks per experiment:
  * the experiment notebook (build_notebook): readable cells that clone the public GitHub repo at the exact
    commit, show the config, train one seed per cell and tabulate the results;
  * the launcher (build_launcher): the kernel Kaggle actually runs. It clones the repo, builds the experiment
    notebook with this script and executes it with nbconvert on the same GPU, so the executed copy, with
    every cell's real outputs, is written to /kaggle/working/<exp>.ipynb. Kaggle's API does not return
    executed notebooks (`kernels pull` gives the source only), so this is how the outputs reach the repo:
    kaggle_run.py downloads the file to notebooks/kaggle/<exp>.ipynb.

CLI (used inside the launcher):
  python scripts/kaggle_notebook.py --exp e5a_afroxlmr_base --config configs/e5a_afroxlmr_base.yaml \
      --module src.train_transformer --seeds 42 43 44 --repo <url> --commit <sha> --out e5a_afroxlmr_base.ipynb
"""
from __future__ import annotations

import argparse
from pathlib import Path

import nbformat as nbf


def config_comment(config_path: Path) -> str:
    """The leading '# ...' lines of a config file, used as the notebook's description."""
    lines = []
    for line in config_path.read_text().splitlines():
        if not line.startswith("#"):
            break
        lines.append(line.lstrip("# ").rstrip())
    return " ".join(lines)


def build_notebook(exp: str, config: str, config_path: Path, module: str, seeds: list[int],
                   extra_args: list[str], repo_url: str, commit: str, uses_embeddings: bool) -> nbf.NotebookNode:
    md, code = nbf.v4.new_markdown_cell, nbf.v4.new_code_cell
    web = repo_url.removesuffix(".git")
    attach = " and attach the `imolara-embeddings` dataset" if uses_embeddings else ""
    cells = [
        md(f"""# Ìmọ̀lára · `{exp}`

{config_comment(config_path)}

Runs `python -m {module} --config {config}` for seeds {", ".join(map(str, seeds))}{" with `" + " ".join(extra_args) + "`" if extra_args else ""} on a Kaggle T4 GPU.

* **Code:** [{web.split("github.com/")[-1]}]({web}) at commit [`{commit[:7]}`]({web}/tree/{commit}), cloned below; nothing is edited inside this notebook.
* **Data:** AfriSenti Yoruba (raw TSVs, pinned commit), downloaded by `src/data.py`.
* **Outputs:** `/kaggle/working/outputs/seed*/` (metrics, dev predictions, run info), downloaded to `results/kaggle/{exp}/` in the repo.
* **Reproduce:** *Copy & Edit*, set Accelerator = GPU T4 and Internet = on{attach}, then *Run all*.

Generated by `scripts/kaggle_run.py --notebook`."""),
        md("## 1 · Setup: clone the repo at the pinned commit, install extras, check the GPU"),
        code(f"""import glob, json, os, subprocess, sys

REPO, COMMIT = "{repo_url}", "{commit}"
CODE, OUT = "/tmp/imolara", "/kaggle/working/outputs"
CONFIG, SEEDS = "{config}", {seeds!r}

subprocess.run(["git", "clone", "-q", REPO, CODE], check=True)
subprocess.run(["git", "-C", CODE, "checkout", "-q", COMMIT], check=True)
subprocess.run([sys.executable, "-m", "pip", "install", "-q", "-r", f"{{CODE}}/requirements-kaggle.txt"], check=True)
# Kaggle ships torchao 0.10, which peft >= 0.20 rejects at import time; we don't use it.
subprocess.run([sys.executable, "-m", "pip", "uninstall", "-y", "-q", "torchao"], check=False)

import torch
assert torch.cuda.is_available(), "No GPU: set Accelerator = GPU T4"
print("GPU:", torch.cuda.get_device_name(0), "| torch", torch.__version__)

os.makedirs(OUT, exist_ok=True)
with open(f"{{OUT}}/env.txt", "w") as f:            # exact package versions, for the report
    subprocess.run([sys.executable, "-m", "pip", "freeze"], stdout=f, check=True)

env = {{**os.environ, "IMOLARA_GIT_COMMIT": COMMIT[:7], "PYTHONUNBUFFERED": "1"}}
emb = glob.glob("/kaggle/input/**/w2v_yo_300.kv", recursive=True)
if emb:                                            # attached imolara-embeddings dataset (RNN runs)
    env["IMOLARA_EMB_DIR"] = os.path.dirname(emb[0])
    print("embeddings:", env["IMOLARA_EMB_DIR"])"""),
        md("## 2 · Experiment configuration"),
        code("print(open(f\"{CODE}/{CONFIG}\").read())"),
        md("## 3 · Training: one cell per seed\n\nThe best epoch is chosen on *clean* dev macro-F1 (dev tweets that do not duplicate a training tweet)."),
        code(f"""def run(seed):
    cmd = [sys.executable, "-m", "{module}", "--config", CONFIG, "--seed", str(seed),
           "--output_dir", f"{{OUT}}/seed{{seed}}", *{extra_args!r}]
    proc = subprocess.Popen(cmd, cwd=CODE, env=env, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
    for line in proc.stdout:
        if not any(noise in line for noise in ("Warning", "warn(", "it/s]", "Loading weights")):
            print(line, end="")
    assert proc.wait() == 0, f"seed {{seed}} failed\""""),
    ]
    cells += [code(f"run({seed})") for seed in seeds]
    cells += [
        md("## 4 · Results across seeds\n\nMacro-F1 is the primary metric; weighted-F1 is the official SemEval-2023 metric. "
           "`clean` excludes tweets that duplicate a training tweet; `no_tones` / `no_diacritics` score the same "
           "tweets with tone marks / all diacritics removed."),
        code("""import pandas as pd

rows = [r for s in SEEDS for r in json.load(open(f"{OUT}/seed{s}/metrics.json"))]
df = pd.DataFrame(rows)
summary = (df.groupby(["split", "subset", "eval_diacritics"])[["macro_f1", "weighted_f1", "accuracy"]]
             .agg(["mean", "std"]).round(4))
summary"""),
        code("""per_seed = df[(df.subset == "clean") & (df.eval_diacritics == "original")][
    ["split", "seed", "macro_f1", "weighted_f1", "f1_negative", "f1_neutral", "f1_positive"]]
per_seed"""),
    ]
    nb = nbf.v4.new_notebook()
    nb["cells"] = cells
    nb["metadata"]["kernelspec"] = {"name": "python3", "display_name": "Python 3", "language": "python"}
    return nb


def build_launcher(exp: str, config: str, module: str, seeds: list[int], extra_args: list[str], repo_url: str,
                   commit: str, uses_embeddings: bool) -> nbf.NotebookNode:
    md, code = nbf.v4.new_markdown_cell, nbf.v4.new_code_cell
    web = repo_url.removesuffix(".git")
    flags = " ".join([f"--extra={a}" for a in extra_args] + (["--embeddings"] if uses_embeddings else []))
    cells = [
        md(f"""# Ìmọ̀lára · `{exp}` (launcher)

This kernel executes the experiment notebook **`{exp}.ipynb`** on this GPU and saves the executed copy, with all its
outputs, as an output file. The executed notebook is in the repo at
[`notebooks/kaggle/{exp}.ipynb`]({web}/blob/main/notebooks/kaggle/{exp}.ipynb); code is
[{web.split("github.com/")[-1]}]({web}) at commit [`{commit[:7]}`]({web}/tree/{commit}).

To reproduce: *Copy & Edit*, set Accelerator = GPU T4 and Internet = on{" and attach `imolara-embeddings`" if uses_embeddings else ""}, then *Run all*."""),
        code(f"""import subprocess, sys
LAUNCH = "/tmp/imolara_launcher"
subprocess.run(["git", "clone", "-q", "{repo_url}", LAUNCH], check=True)
subprocess.run(["git", "-C", LAUNCH, "checkout", "-q", "{commit}"], check=True)
subprocess.run([sys.executable, f"{{LAUNCH}}/scripts/kaggle_notebook.py", "--exp", "{exp}", "--config", "{config}",
                "--module", "{module}", "--seeds", *map(str, {seeds!r}), "--repo", "{repo_url}", "--commit", "{commit}",
                *"{flags}".split(), "--out", "/tmp/{exp}.ipynb"], check=True)"""),
        code(f"""# Execute the experiment notebook here; the executed copy is saved to /kaggle/working/{exp}.ipynb
result = subprocess.run(["jupyter", "nbconvert", "--to", "notebook", "--execute", "/tmp/{exp}.ipynb",
                         "--ExecutePreprocessor.timeout=-1", "--ExecutePreprocessor.kernel_name=python3",
                         "--output-dir", "/kaggle/working", "--output", "{exp}.ipynb"],
                        capture_output=True, text=True)
print(result.stderr[-3000:])
assert result.returncode == 0, "experiment notebook failed; see the executed copy in the outputs"
"""),
        code("""import json, glob, pandas as pd
rows = [r for f in sorted(glob.glob("/kaggle/working/outputs/seed*/metrics.json")) for r in json.load(open(f))]
df = pd.DataFrame(rows)
df.groupby(["split", "subset", "eval_diacritics"])[["macro_f1", "weighted_f1"]].agg(["mean", "std"]).round(4)"""),
    ]
    nb = nbf.v4.new_notebook()
    nb["cells"] = cells
    nb["metadata"]["kernelspec"] = {"name": "python3", "display_name": "Python 3", "language": "python"}
    return nb


def main():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--exp", required=True)
    p.add_argument("--config", required=True)
    p.add_argument("--module", required=True)
    p.add_argument("--seeds", nargs="+", type=int, required=True)
    p.add_argument("--extra", action="append", default=[], help="extra argument for the training module")
    p.add_argument("--repo", required=True)
    p.add_argument("--commit", required=True)
    p.add_argument("--embeddings", action="store_true")
    p.add_argument("--out", required=True)
    a = p.parse_args()
    root = Path(__file__).resolve().parents[1]
    nb = build_notebook(a.exp, a.config, root / a.config, a.module, a.seeds, a.extra, a.repo, a.commit, a.embeddings)
    nbf.write(nb, a.out)


if __name__ == "__main__":
    main()
