"""Statistical label-noise estimate with confident learning (Northcutt, Jiang & Chuang, 2021, JAIR).

  python -m src.label_noise        # writes results/error_analysis/label_noise.md and label_issues_*.csv

Instead of judging by reading which tweets are mislabelled, we let held-out model probabilities decide:
  1. 5-fold cross-validation of the E1c TF-IDF model on the training set gives an out-of-fold probability
     p(class | tweet) for every training tweet (no tweet is scored by a model that saw it).
  2. Per-class confidence threshold t_j = mean p(j) over tweets whose given label is j.
  3. A tweet is "confidently counted" as class j if p(j) >= t_j (the highest such class if several).
     The confident joint C[given, confident] counts these; off-diagonal mass estimates label errors.
  4. Flagged label issues = tweets whose confident class differs from the given label.
For dev/test we score with a model trained on all of train and reuse the training thresholds, then check how the
human/model-assisted 'likely label noise' tags agree with the statistical flags.
"""
from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.model_selection import StratifiedKFold

from src.baselines import build_model
from src.data import LABELS, load_eval_split, load_split, preprocess_frame

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "results" / "error_analysis"
SPEC, PARAMS = {"model": "logreg", "features": "word+char"}, {"C": 3, "class_weight": None}   # E1c


def out_of_fold_probs(df: pd.DataFrame, folds: int = 5, seed: int = 0) -> np.ndarray:
    probs = np.zeros((len(df), len(LABELS)))
    for train_idx, held_idx in StratifiedKFold(folds, shuffle=True, random_state=seed).split(df, df["label_id"]):
        model = build_model(SPEC, PARAMS, seed).fit(df["text"].iloc[train_idx], df["label_id"].iloc[train_idx])
        probs[held_idx] = model.predict_proba(df["text"].iloc[held_idx])
    return probs


def thresholds(probs: np.ndarray, labels: np.ndarray) -> np.ndarray:
    return np.array([probs[labels == j, j].mean() for j in range(len(LABELS))])


def confident_class(probs: np.ndarray, t: np.ndarray) -> np.ndarray:
    """Most probable class among those clearing their threshold; -1 if none does."""
    above = np.where(probs >= t, probs, -1.0)
    out = above.argmax(axis=1)
    out[(above < 0).all(axis=1)] = -1
    return out


def confident_joint(labels: np.ndarray, conf: np.ndarray) -> pd.DataFrame:
    keep = conf >= 0
    cj = pd.crosstab(pd.Series(labels[keep]).map(dict(enumerate(LABELS))).rename("given label"),
                     pd.Series(conf[keep]).map(dict(enumerate(LABELS))).rename("confident class"))
    return cj.reindex(index=LABELS, columns=LABELS, fill_value=0)


def flag(df: pd.DataFrame, probs: np.ndarray, t: np.ndarray) -> pd.DataFrame:
    conf = confident_class(probs, t)
    out = df[["id", "text", "label"]].copy()
    out["confident_class"] = [LABELS[c] if c >= 0 else "" for c in conf]
    out["p_given"] = probs[np.arange(len(df)), df["label_id"].to_numpy()].round(4)
    out["p_confident"] = [round(probs[i, c], 4) if c >= 0 else np.nan for i, c in enumerate(conf)]
    out["issue"] = (conf >= 0) & (conf != df["label_id"].to_numpy())
    # rank by how strongly the model prefers another class over the given one (self-confidence ordering)
    out["margin"] = (out["p_confident"] - out["p_given"]).round(4)
    return out


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    train = preprocess_frame(load_split("yor", "train"))
    probs = out_of_fold_probs(train)
    labels = train["label_id"].to_numpy()
    t = thresholds(probs, labels)
    cj = confident_joint(labels, confident_class(probs, t))
    train_flags = flag(train, probs, t)
    rate = train_flags["issue"].mean()

    # dev/test: model trained on all of train, thresholds from the training cross-validation
    model = build_model(SPEC, PARAMS, 0).fit(train["text"], train["label_id"])
    parts = ["# Statistical label-noise estimate (confident learning)", "",
             "_Generated by `python -m src.label_noise`. Method: Northcutt, Jiang & Chuang (2021), confident learning; "
             "out-of-fold probabilities from 5-fold cross-validation of the E1c TF-IDF model. A flag means a held-out "
             "model is confidently in favour of a different class than the annotators chose. It marks a **candidate** "
             "label error (or a genuinely ambiguous tweet), not proof._", "",
             f"Per-class thresholds t_j (mean self-confidence): " +
             ", ".join(f"{l} {v:.3f}" for l, v in zip(LABELS, t)), "",
             "## Confident joint on the training set (rows: given label, columns: confident class)", "",
             cj.to_markdown(), "",
             f"**Estimated share of training tweets with a likely label issue: {rate:.1%}** "
             f"({int(train_flags['issue'].sum()):,} of {len(train):,}). "
             f"For comparison, the AfriSenti annotators' agreement on Yoruba is κ = 0.65.", ""]
    per_class = train_flags.groupby("label")["issue"].mean().reindex(LABELS)
    parts += ["Flag rate by given label: " + ", ".join(f"{l} {v:.1%}" for l, v in per_class.items()), ""]
    train_flags[train_flags["issue"]].sort_values("margin", ascending=False) \
        .to_csv(OUT / "label_issues_train.csv", index=False)

    for split in ("dev", "test"):
        df = preprocess_frame(load_eval_split("yor", split))
        f = flag(df, model.predict_proba(df["text"]), t)
        f["overlap_train"] = df["overlap_train"].to_numpy()
        f[f["issue"]].sort_values("margin", ascending=False).to_csv(OUT / f"label_issues_{split}.csv", index=False)
        parts.append(f"- {split}: {f['issue'].mean():.1%} of tweets flagged ({int(f['issue'].sum()):,} of {len(f):,})")
        if split == "test":
            test_flags = f.set_index("id")
    parts.append("")

    tagged = OUT / "errors_tagged.csv"
    if tagged.exists():   # how do the reading-based tags relate to the statistical flags?
        tags = pd.read_csv(tagged)
        tags["flagged"] = tags["id"].map(test_flags["issue"])
        tags["tagged_noise"] = tags["category"].fillna("").str.contains("likely label noise")
        ct = pd.crosstab(tags["tagged_noise"].map({True: "tagged 'likely label noise'", False: "not tagged"}),
                         tags["flagged"].map({True: "flagged by CL", False: "not flagged"}), margins=True)
        parts += ["## Reading-based tags vs statistical flags (the 100 sampled test errors)", "", ct.to_markdown(), "",
                  "_All 100 tweets are model errors, so many are flagged. The question is whether tweets tagged as "
                  "'likely label noise' are flagged more often than the rest._", ""]
        by_cat = (tags.assign(category=tags["category"].str.split(";")).explode("category")
                  .groupby("category")["flagged"].agg(["count", "mean"]).sort_values("mean", ascending=False))
        by_cat["mean"] = (100 * by_cat["mean"]).round(0).astype(int).astype(str) + "%"
        parts += ["Flag rate by tagged category:", "", by_cat.rename(columns={"count": "n", "mean": "flagged"}).to_markdown(), ""]

    (OUT / "label_noise.md").write_text("\n".join(parts))
    print((OUT / "label_noise.md").read_text())


if __name__ == "__main__":
    main()
