"""Summarise results/experiments.csv into the tables used in the README and report.

  python -m src.summarize            # writes results/summary.md

Main table: clean-dev macro-F1 (selection metric) plus all-dev macro/weighted-F1, as mean ± std over
seeds (deterministic models have one run). Robustness table: macro-F1 per evaluation diacritic form.
"""
from __future__ import annotations

from pathlib import Path

import pandas as pd

from src.evaluate import EXPERIMENTS_CSV

ROOT = Path(__file__).resolve().parents[1]
SUMMARY_MD = ROOT / "results" / "summary.md"


def _fmt(values: pd.Series) -> str:
    values = values.dropna()
    if values.empty:
        return "–"
    if len(values) == 1:
        return f"{values.iloc[0]:.3f}"
    return f"{values.mean():.3f} ± {values.std(ddof=1):.3f}"


def main_table(df: pd.DataFrame, split: str = "dev") -> pd.DataFrame:
    df = df[(df["split"] == split) & (df["eval_diacritics"] == "original")]
    rows = []
    for exp_id, g in df.groupby("exp_id", sort=False):
        clean, full = g[g["subset"] == "clean"], g[g["subset"] == "all"]
        rows.append({"experiment": exp_id, "model": g["model"].iloc[0], "seeds": g["seed"].nunique(),
                     f"macro-F1 (clean {split})": _fmt(clean["macro_f1"]),
                     f"macro-F1 (all {split})": _fmt(full["macro_f1"]),
                     f"weighted-F1 (all {split})": _fmt(full["weighted_f1"]),
                     "F1 neg / neu / pos (clean)": " / ".join(f"{clean[c].mean():.2f}" for c in
                                                            ("f1_negative", "f1_neutral", "f1_positive")),
                     "_sort": clean["macro_f1"].mean()})
    return pd.DataFrame(rows).sort_values("_sort").drop(columns="_sort")


def robustness_table(df: pd.DataFrame, split: str = "dev") -> pd.DataFrame:
    df = df[(df["split"] == split) & (df["subset"] == "clean")]
    table = df.pivot_table(index="exp_id", columns="eval_diacritics", values="macro_f1", aggfunc="mean")
    table = table.reindex(columns=[c for c in ("original", "no_tones", "no_diacritics") if c in table])
    if "original" in table:
        for col in table.columns.drop("original"):
            table[f"Δ {col}"] = table[col] - table["original"]
    return table.round(3)


def main():
    df = pd.read_csv(EXPERIMENTS_CSV)
    parts = ["# Results summary", "",
             "_Generated by `python -m src.summarize` from `results/experiments.csv`. "
             "Selection metric: clean-dev macro-F1 (dev tweets that do not duplicate a training tweet)._", "",
             "## Main results (dev, original diacritics)", "", main_table(df).to_markdown(index=False), "",
             "## Diacritic robustness (clean dev macro-F1 by evaluation form)", "",
             robustness_table(df).to_markdown(), ""]
    if (df["split"] == "test").any():
        parts += ["## Test (Phase 6)", "", main_table(df, "test").to_markdown(index=False), ""]
    SUMMARY_MD.write_text("\n".join(parts))
    print(SUMMARY_MD.read_text())


if __name__ == "__main__":
    main()
